<a href="https://colab.research.google.com/github/MahdiZakipour/ML-MSc-Thesis/blob/main/A_Z_Machine_Learning_1_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# working directory
import os
os.chdir('D:\Learning\Deep Learning A-Z course - my files\Section 1 Data Pre-processing\Section 3 - Data Preprocessing in Python\Python')
os.getcwd()

# import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# import data set
dataset = pd.read_csv('D:\Learning\Deep Learning A-Z course - my files\Section 1 Data Pre-processing\Section 3 - Data Preprocessing in Python\Python\Data.csv')
print(dataset)

x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
#print(y)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
# taking care of missing data /// Numercal
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x[:, 1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
#  Categorical data - dummy ENCODING  - OneHotEncoding
# to Encode x :
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x.fit_transform(x[:, 0])



from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
x = ct.fit_transform(x)

print(x)

# to Encode y :
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

print(y)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]


D:\Softwares\AnacondaSetUp\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [ ]:
# splitting the data into Test and Training set
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
# feature Scaling /// NORMALIZATION - or - STANDARADIZATION
from sklearn.preprocessing import StandardScaler

scale_x = StandardScaler()
x_train[:, 1:3] = scale_x.fit_transform(x_train[:, 1:3])
x_test[:, 1:3] = scale_x.transform(x_test[:, 1:3])

In [ ]:
### THIS BLOCK was ADDED, seperately. So be carefull with the names.

### Feature Observation
# making some Assumptions for our Data, We’ll find out if these assumptions are correct through the project.

### Exploratory Data Analysis
import matplotlib.pyplot as plt
import seaborn as sns # for making statistical graphics
#                       Plot pairwise relationships in a dataset; Histograms and Scatters TOGATHER :)

%matplotlib inline

# Calculate and show pairplot
sns.pairplot(data, size=2.5)
plt.tight_layout()

NameError: name 'data' is not defined

In [ ]:
x_train

array([[0.0, 2.6457513110645903, -0.7745966692414834, 40.0,
        63777.77777777778],
       [1.0, -0.3779644730092272, -0.7745966692414834, 37.0, 67000.0],
       [0.0, -0.3779644730092272, 1.2909944487358056, 27.0, 48000.0],
       [0.0, -0.3779644730092272, 1.2909944487358056, 38.77777777777778,
        52000.0],
       [1.0, -0.3779644730092272, -0.7745966692414834, 48.0, 79000.0],
       [0.0, -0.3779644730092272, 1.2909944487358056, 38.0, 61000.0],
       [1.0, -0.3779644730092272, -0.7745966692414834, 44.0, 72000.0],
       [1.0, -0.3779644730092272, -0.7745966692414834, 35.0, 58000.0]],
      dtype=object)

In [ ]:
x_test

array([[0.0, 2.6457513110645903, -0.7745966692414834, 30.0, 54000.0],
       [0.0, 2.6457513110645903, -0.7745966692414834, 50.0, 83000.0]],
      dtype=object)

In [ ]:
onehotencoder

OneHotEncoder(categories=array([0., 1., 1., 1., 1., 0., 1., 0., 1., 0.]))